//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int Id { get; set; }
        public Nullable<int> id_ped { get; set; }
        public Nullable<int> id_pro { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio_venta { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> Importe { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
